### PR TITLE
fix(JS/RN/Flutter): update docs to include switcher for adding auth via CLI or existing resources

### LINKED ISSUE #5216: [Feedback](JS/RN) Auth re-use existing backend page has out of date instructions for configuration
**Page**: [`/lib/auth/start/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/start/q/platform/react-native)

**Nit**:

indent spacing of 4 spaces per tab in `#Re-use existing authentication resource` section looks bad on smaller screens

**JS Feedback**:

The JS page has instructions that are related to react native that should not be there. In the `#Configure your application` section, 2nd and 3rd code blocks plus headings should be removed

**RN Feedback**:

The RN page shows out of date instructions. `aws-amplify-react-native` is on its way to deprecation and is an old UI package that is not necessary to install just because the user is trying to add Auth. 
Also `react-native link` is no longer required as with v0.60+ it is a redundant command. [Autolinking is now enabled](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md#autolinking) through the react-native CLI

### PR DESCRIPTION
**Pull request by cwomack**
#### Description of changes:
Updates to "Getting Started" sections where authentication is added to project within JS, RN, Flutter, Android, and Swift frameworks. 

#### Related GitHub issue #, if available: N/A
Resolves #5216 

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [x] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [x] JS
- [ ] iOS
- [ ] Android
- [x] Flutter
- [x] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br />
      _ref: MDX: `[link](https://link.com)`
            HTML: `<a href="https://link.com">link</a>`_
            
### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

File: src/directory/directory.js [hunk 1]
```diff
@@ -93,11 +93,6 @@ const directory = {
             route: '/lib/analytics/enable-disable',
             filters: ['android', 'flutter', 'ios', 'js', 'react-native']
           },
-          {
-            title: 'Identify user',
-            route: '/lib/analytics/identifyuser',
-            filters: ['android', 'flutter', 'ios', 'react-native', 'js']
```
Comment (tannerabread) [inline src/directory/directory.js:99]: This change seems unrelated to the rest, was it intended to remove android/flutter/ios as well? Those seem to have information

**Review by tannerabread — DISMISSED** [review]

File: src/fragments/lib/auth/js/getting-started.mdx [hunk 2]
```diff
@@ -4,11 +4,14 @@
 
 Amplify uses [Amazon Cognito](https://aws.amazon.com/cognito/) as the main authentication provider. Amazon Cognito is a robust user directory service that handles user registration, authentication, account recovery & other operations. In this tutorial, you'll learn how to add authentication to your application using Amazon Cognito and username/password login.
 
-## Create authentication service
+## Set Up Backend Resources
 
-To start from scratch, run the following command in your project's root folder:
+To use Authentication with Amplify, you have the option to either have the Amplify CLI setup resources for you, or you can use an existing Amazon Cognito resource in your AWS account.
```
[the remark this answers is not in the document]
Comment (abdallahshaban557) [reply src/fragments/lib/auth/js/getting-started.mdx:9]: I like that suggestion. We'll probably have to do the same for push notifications

File: src/fragments/lib/auth/js/getting-started.mdx [hunk 3]
```diff
@@ -4,11 +4,14 @@
...
 
-> If you want to re-use an existing authentication resource from AWS (e.g. Amazon Cognito UserPool or Identity Pool) refer to [this section](/lib/auth/start#re-use-existing-authentication-resource).
+<BlockSwitcher>
+<Block name="Amplify CLI">
+
+If you have previously enabled an Amplify category that uses Auth behind the scenes, e.g. API category, you may already have an Auth configuration. In such a case, run `amplify auth update` command to edit your configuration. To start from scratch, run the following command in your project's root folder:
```
[the remark this answers is not in the document]
Comment (abdallahshaban557) [reply src/fragments/lib/auth/js/getting-started.mdx:14]: I think both might work - but we should change it to `amplify update auth`

[the remark this answers is not in the document]
Comment (abdallahshaban557) [reply src/fragments/lib/auth/js/getting-started.mdx:14]: Looking at it more - I think we should simplify this and just keep things before the add command to

To set up the resources you need for Authentication, run the following command in your project's rood folder:

File: src/directory/directory.js (hunk 1 above)
Comment (cwomack) [reply src/directory/directory.js:99]: Good catch Bannon.  This was a change tied to some of the Analytics changes I have locally that got included with the directory.js file updates.  While this is a needed removal, it isn't within scope of this PR overall.  I'll add it back in and save it to be included with all the Analytics changes.

File: src/fragments/lib/auth/js/getting-started.mdx (hunk 3 above)
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx:14]: @tannerabread, I'll update the CLI command.  As for the simplification of the sentences, @abdallahshaban557 are you saying BOTH sentences should be removed and simplified to just the following: 

"To set up the resources needed for Authentication, run the following command in your project's root folder:"

[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx:14]: Or did you mean update only the second sentence to that?

File: src/fragments/lib/auth/js/getting-started.mdx (hunk 2 above)
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx:9]: Updated this sentence on all 3 instances where the preamble was added.

File: src/fragments/lib/auth/js/getting-started.mdx [hunk 4]
```diff
@@ -31,6 +42,95 @@ Now, the authentication service has been deployed and you can start using it. To
 ```bash
 amplify console
 ```
+</Block>
+<Block name="Existing resources">
+
+If you want to re-use an existing authentication resource from AWS (e.g. Amazon Cognito UserPool or Identity Pool), update `Amplify.configure()` method with the following information.
```
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx:48]: @tannerabread, that's a great callout.  Would the best solution be to move the [#Configure you application](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#configure-your-application) section to be included WITHIN the switcher for the "Amplify CLI" block?

[the remark this answers is not in the document]
Comment (tannerabread) [reply src/fragments/lib/auth/js/getting-started.mdx:48]: That was my thought, just watch that if you do it this way that section also included the actual install of the amplify package so that would need to be included either before the block switcher (seems better to me) or _also_ in the existing resources section.

Also noticed that I was originally checking this under React Native selector and the JS page has the pre-built UI components which also include the install of the amplify package and `Amplify.configure(awsExports)` so maybe all the configuring could be handled in that top section and the installs elsewhere. Additionally with these UI sections, they import the resources as `awsExports` while the #Configure your application section called it `awsconfig`. Additionally additionally those 4 block switches are inconsistent with each other, not sure if that's something you'd want to handle in this PR

[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx:48]: @tannerabread, that's a valid point and something I've seen as well.  Since we're doing `export default` from the `aws-exports.js` it won't matter as much, but agreed that our naming convention should be consistent within our docs to avoid confusion.  

Maybe that aspect can be addressed with a separate PR?  I can include it within this one but for now, I'll make minimal updates per the advice above on the BlockSwitcher including the "configure your application" steps.  As far as whether or not it should be above the BlockSwitcher, @abdallahshaban557 is there any preference here? 

I'd agree that having the `npm install aws-amplify` command could be above, but we'd need to just add some different verbiage around the `Amplify.configure()` part for CLI block.

File: src/fragments/lib/auth/js/getting-started.mdx (hunk 3 above)
[the remark this answers is not in the document]
Comment (abdallahshaban557) [reply src/fragments/lib/auth/js/getting-started.mdx:14]: I think we should remove everything except that sentence.

[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx]: Updated this section to have the same simplified sentence as the Push Notifications PR.

File: src/fragments/lib/auth/js/getting-started.mdx (hunk 4 above)
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/js/getting-started.mdx]: Updated to include the "Existing Amazon resources..." verbiage of Push Notifications PR and also lifted the Config/Dependencies that were within the Blockswitcher to be above the switcher now.  There's a minimal sentence with link to the "Install Amplify Libraries" mirror the Push Notification PR as well. 

@abdallahshaban557, I put it ABOVE the Blockswitcher so that a customer isn't running through this section and then doesn't see the "Note that before..." until the end.  By placing it above the switcher, it also eliminates the text being duplicated in both blocks of the switcher.

**Review by tannerabread — COMMENTED** [review]
This all looks a lot better, are we ignoring the installation instructions in the UI sections for now for JS?

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 5]
```diff
@@ -21,7 +21,14 @@ import flutter2 from "/src/fragments/lib/auth/flutter/getting_started/10_preReq.
 
 <Fragments fragments={{flutter: flutter2}} />
 
-## Configure Auth Category
+## Set Up Backend Resources
+
+To use Authentication with Amplify, you can choose to configure resources through the Amplify CLI (which will automatically create them on the backend for you) or use an existing Amazon Cognito resource in your AWS account.
+
+> Note that before you can add an AWS resource to your application, the application must have the Amplify libraries installed. If you need to perform this step, see [Install Amplify Libraries](/lib/project-setup/create-application#n2-install-amplify-libraries) and ensure you've installed the necessary dependencies.
```
Comment (HuiSF) [inline src/fragments/lib/auth/native_common/getting_started/common.mdx:28]: I read this as an important note here, should use the `Callout` block instead of the Quote block?

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 6]
```diff
@@ -39,6 +46,8 @@ Enter the following when prompted:
     `No, I am done.`
 ```
 
+> If you have previously enabled an Amplify category that uses Auth behind the scenes (e.g. API category), run the `amplify update auth` command to edit your configuration.
```
Comment (HuiSF) [inline src/fragments/lib/auth/native_common/getting_started/common.mdx:49]: Ditto could consider to use the `Callout` block.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 7]
```diff
@@ -57,6 +66,88 @@ import flutter5 from "/src/fragments/lib/auth/flutter/getting_started/12_amplify
...
+<Block name="Existing resources">
+Existing Authentication resources from AWS (e.g. Amazon Cognito UserPools or Identity Pools) can be used with the Amplify Libraries by running:
+
+```bash
+amplify import auth
+```
+
+For more details, see how to [Use an existing Cognito User Pool and Identity Pool](/cli/auth/import).
+
+If you are not using the Amplify CLI, a Cognito User Pool and Identity Pool can be used by referencing them in your `amplifyconfiguration.json` file.
```
Comment (HuiSF) [inline src/fragments/lib/auth/native_common/getting_started/common.mdx:79]:
```suggestion
If you are not using the Amplify CLI, a Cognito User Pool and Identity Pool can be used by referencing them in your `amplifyconfiguration.json` or `amplifyconfiguration.dart` file.
```

In amplify-flutter, the file would be `amplifyconfiguration.dart`. The suggestion is from this [reference](https://docs.amplify.aws/cli/start/workflows/#amplify-pull).

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 8]
```diff
@@ -116,13 +152,13 @@ If you are not using the Amplify CLI, a Cognito User Pool and Identity Pool can
                                 "profile",
                                 "aws.cognito.signin.user.admin"
                             ]
-                        }
+                        },
```
Comment (HuiSF) [inline src/fragments/lib/auth/native_common/getting_started/common.mdx:155]: nit: this trailing comma make it invalid json string...

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 9]
```diff
@@ -67,19 +68,54 @@ import flutter5 from "/src/fragments/lib/auth/flutter/getting_started/12_amplify
...
+
+```bash
+amplify console
+```
 For more details, see how to [Use an existing Cognito User Pool and Identity Pool](/cli/auth/import).
 
-If you are not using the Amplify CLI, a Cognito User Pool and Identity Pool can be used by referencing them in your `amplifyconfiguration.json` file.
+</Block>
+
+<Block name="Manual Configuration">
```
Comment (HuiSF) [inline src/fragments/lib/auth/native_common/getting_started/common.mdx:109]: The switcher looks great and clear. Thanks for the update 👍

The content of `common.mdx` is rendered for amplify-swift and amplify-android libraries documentations as well. Might need to create platform specific content and import per platform here. Example [here](https://github.com/aws-amplify/docs/blob/88915b19fc63858cadac2d34597c1c0c99f94889/src/fragments/lib/auth/existing-resources.mdx?plain=1#L10-L15).

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+      - **PoolID**: ID of the Amazon Cognito Identity Pool (e.g. `us-east-1:123e4567-e89b-12d3-a456-426614174000`)
+      - **Region**: AWS Region where the resources are provisioned (e.g. `us-east-1`)
+- **CognitoUserPool**:
+  - **Default**:
+    - **PoolId**: ID of the Amazon Cognito User Pool (e.g. `us-east-1_abcdefghi`)
+    - **AppClientId**: ID for the client used to authenticate against the user pool
+    - **Region**: AWS Region where the resources are provisioned (e.g. `us-east-1`)
+- **Auth**:
+  - **Default**:
+    - **authenticationFlowType**: The authentication flow type, takes values `USER_SRP_AUTH`, `CUSTOM_AUTH`. Default is `USER_SRP_AUTH`.
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:148]:
```suggestion
    - **authenticationFlowType**: The authentication flow type, takes values `USER_SRP_AUTH`, `CUSTOM_AUTH`, and `USER_PASSWORD_AUTH`. Default is `USER_SRP_AUTH`.
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+   Cognito User Pool and Identity Pool
+   Cognito User Pool only
+```
+
+Once you've selected an option, you'll be able to search for and import an existing Cognito User Pool and Identity Pool (or User Pool only) within your AWS account.  The `amplify import auth` command will also do the following:
+- Automatically populate your Amplify Library configuration files (`amplifyconfiguration.dart` and `amplifyconfiguration.json`) with your chosen Amazon Cognito resource information
+- Provide your designated existing Cognito resource as the authentication & authorization mechanism for all auth-dependent categories (API, Storage and more)
+- Enable Lambda functions to access the chosen Cognito resource if you permit it
+
+> If you have previously enabled an Amplify category that uses Auth behind the scenes (e.g. API category), run `amplify update auth` command to edit your configuration.
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:64]: I would remove this - I really don't understand it in the context of importing.

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 12]
```diff
@@ -0,0 +1,155 @@
...
+amplify import auth
+```
+```console
+? What type of auth resource do you want to import?
+   Cognito User Pool and Identity Pool
+   Cognito User Pool only
+```
+
+Once you've selected an option, you'll be able to search for and import an existing Cognito User Pool and Identity Pool (or User Pool only) within your AWS account.  The `amplify import auth` command will also do the following:
+- Automatically populate your Amplify Library configuration files (`amplifyconfiguration.dart` and `amplifyconfiguration.json`) with your chosen Amazon Cognito resource information
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:60]:
```suggestion
- Automatically populate your Amplify Library configuration file (`amplifyconfiguration.dart`) with your chosen Amazon Cognito resource information
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 13]
```diff
@@ -0,0 +1,155 @@
...
+
+import flutter5 from "/src/fragments/lib/auth/flutter/getting_started/12_amplifyConfig.mdx";
+
+<Fragments fragments={{flutter: flutter5}} />
+
+</Block>
+
+<Block name="Amplify CLI (Import)">
+
+> Prerequisites: [Install and configure](/lib/project-setup/prereq/q/platform/flutter/#install-and-configure-the-amplify-cli) the Amplify CLI in addition to the Amplify libraries and [necessary dependencies](/lib/project-setup/create-application/q/platform/flutter/#2-install-amplify-libraries).
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:46]:
```suggestion
> Prerequisites: [Install and configure](/lib/project-setup/prereq/q/platform/flutter/#install-and-configure-the-amplify-cli) the Amplify CLI in addition to the Amplify libraries and [necessary dependencies](/lib/auth/getting-started/q/platform/flutter/#install-amplify-libraries).
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 14]
```diff
@@ -0,0 +1,155 @@
+<BlockSwitcher>
+<Block name="Amplify CLI (Create)">
+
+> Prerequisites: [Install and configure](/lib/project-setup/prereq/q/platform/flutter/#install-and-configure-the-amplify-cli) the Amplify CLI in addition to the Amplify libraries and [necessary dependencies](/lib/project-setup/create-application/q/platform/flutter/#2-install-amplify-libraries).
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:4]:
```suggestion
> Prerequisites: [Install and configure](/lib/project-setup/prereq/q/platform/flutter/#install-and-configure-the-amplify-cli) the Amplify CLI in addition to the Amplify libraries and [necessary dependencies](/lib/auth/getting-started/q/platform/flutter/#install-amplify-libraries).
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 15]
```diff
@@ -0,0 +1,155 @@
...
+
+</Block>
+
+<Block name="Manual Configuration">
+
+Existing Authentication resources from AWS (e.g. Amazon Cognito UserPools or Identity Pools) can be used with the Amplify Libraries by calling the `Amplify.configure()` method.
+
+If you are not using the Amplify CLI, a Cognito User Pool and Identity Pool can be used by referencing them in your `amplifyconfiguration.dart` file:
+
+```jsx
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:87]:
```suggestion
```dart
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 16]
```diff
@@ -0,0 +1,155 @@
...
+    - **PoolId**: ID of the Amazon Cognito User Pool (e.g. `us-east-1_abcdefghi`)
+    - **AppClientId**: ID for the client used to authenticate against the user pool
+    - **Region**: AWS Region where the resources are provisioned (e.g. `us-east-1`)
+- **Auth**:
+  - **Default**:
+    - **authenticationFlowType**: The authentication flow type, takes values `USER_SRP_AUTH`, `CUSTOM_AUTH`. Default is `USER_SRP_AUTH`.
+    - **OAuth**: Hosted UI Configuration (only include this if using the Hosted UI flow)
+      - **Scopes:** Scopes should match the scopes enables in Cognito under "App client settings"
+    
+If you are using a Cognito User Pool, without a Cognito Identity Pool, you can omit the **CredentialsProvider** section in the configuration.
```
Comment (dnys1) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:152]:
```suggestion
If you are using a Cognito User Pool without a Cognito Identity Pool, you can omit the **CredentialsProvider** section in the configuration.
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx (hunk 14 above)
Comment (cwomack) [reply src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx]: Updated in most recent commit.

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx (hunk 13 above)
Comment (cwomack) [reply src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx]: Updated in most recent commit.

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx (hunk 12 above)
Comment (cwomack) [reply src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx]: Nice catch! Fixed with newest commit.

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx (hunk 11 above)
Comment (cwomack) [reply src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx]: Updated in most recent commit.  I went ahead and removed it as an unordered list/bullet point since it doesn't makes sense with just 1.

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx (hunk 10 above)
Comment (cwomack) [reply src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx]: Updated in most recent commit. Glad you caught this so an option wasn't missing.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 17]
```diff
@@ -57,6 +67,121 @@ import flutter5 from "/src/fragments/lib/auth/flutter/getting_started/12_amplify
...
+    - **PoolId**: ID of the Amazon Cognito User Pool (e.g. `us-east-1_abcdefghi`)
+    - **AppClientId**: ID for the client used to authenticate against the user pool
+    - **Region**: AWS Region where the resources are provisioned (e.g. `us-east-1`)
+- **Auth**:
+  - **Default**:
+    - **authenticationFlowType**: The authentication flow type, takes values `USER_SRP_AUTH`, `CUSTOM_AUTH`. Default is `USER_SRP_AUTH`.
+    - **OAuth**: Hosted UI Configuration (only include this if using the Hosted UI flow)
+      - **Scopes:** Scopes should match the scopes enables in Cognito under "App client settings"
+    
+If you are using a Cognito User Pool, without a Cognito Identity Pool, you can omit the **CredentialsProvider** section in the configuration.
```
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Updated this in most recent commit, great catch.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 18]
```diff
@@ -57,6 +67,121 @@ import flutter5 from "/src/fragments/lib/auth/flutter/getting_started/12_amplify
...
+      - **PoolID**: ID of the Amazon Cognito Identity Pool (e.g. `us-east-1:123e4567-e89b-12d3-a456-426614174000`)
+      - **Region**: AWS Region where the resources are provisioned (e.g. `us-east-1`)
+- **CognitoUserPool**:
+  - **Default**:
+    - **PoolId**: ID of the Amazon Cognito User Pool (e.g. `us-east-1_abcdefghi`)
+    - **AppClientId**: ID for the client used to authenticate against the user pool
+    - **Region**: AWS Region where the resources are provisioned (e.g. `us-east-1`)
+- **Auth**:
+  - **Default**:
+    - **authenticationFlowType**: The authentication flow type, takes values `USER_SRP_AUTH`, `CUSTOM_AUTH`. Default is `USER_SRP_AUTH`.
```
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Updated in most recent commit. Glad you caught this so an option wasn't missing.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx (hunk 8 above)
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Great catch, fixed with most recent commit.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx (hunk 6 above)
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Valid point.  I've updated all references to this to be within a `<Callout>` now.  Let me know if this looks better. 

CC: @abdallahshaban557

File: src/fragments/lib/auth/native_common/getting_started/common.mdx (hunk 5 above)
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Valid point.  I've updated all references to this to be within a `<Callout>` now.  Let me know if this looks better.  

This one was before the more recent updates/latest commit tat dropped the "> Note that..." into the block switcher.    

CC: @abdallahshaban557

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 19]
```diff
@@ -21,7 +22,14 @@ import flutter2 from "/src/fragments/lib/auth/flutter/getting_started/10_preReq.
...
 
-## Configure Auth Category
+## Set Up Backend Resources
+
+To use Authentication with Amplify, you have the option to set up or import existing Amazon Cognito resources via the Amplify CLI or manually configure them in your application.
+
+<BlockSwitcher>
+<Block name="Amplify CLI (Create)">
+
+> Prerequisites: [Install and configure](/lib/project-setup/prereq/q/platform/flutter/#install-and-configure-the-amplify-cli) the Amplify CLI in addition to the Amplify libraries and [necessary dependencies](/lib/project-setup/create-application/q/platform/flutter/#2-install-amplify-libraries).
```
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Should be fixed with most recent commit.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx [hunk 20]
```diff
@@ -57,6 +67,121 @@ import flutter5 from "/src/fragments/lib/auth/flutter/getting_started/12_amplify
 
 <Fragments fragments={{flutter: flutter5}} />
 
+</Block>
+
+<Block name="Amplify CLI (Import)">
+
+> Prerequisites: [Install and configure](/lib/project-setup/prereq/q/platform/flutter/#install-and-configure-the-amplify-cli) the Amplify CLI in addition to the Amplify libraries and [necessary dependencies](/lib/project-setup/create-application/q/platform/flutter/#2-install-amplify-libraries).
```
[the remark this answers is not in the document]
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Should be fixed with most recent commit.

File: src/fragments/lib/auth/native_common/getting_started/common.mdx (hunk 6 above)
Comment (cwomack) [reply src/fragments/lib/auth/native_common/getting_started/common.mdx]: Reverting these back after reviewing with PM.

File: src/fragments/lib/auth/android/getting_started/50_configureBackend.mdx [hunk 21]
```diff
@@ -0,0 +1,143 @@
...
+                                "profile",
+                                "aws.cognito.signin.user.admin"
+                            ]
+                        }
+                    }
+                }
+            }
+        }
+    }
+}
```
Comment (tannerabread) [inline src/fragments/lib/auth/android/getting_started/50_configureBackend.mdx:121]:
```suggestion
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "[COGNITO IDENTITY POOL ID]",
              "Region": "[REGION]"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "[COGNITO USER POOL ID]",
            "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
            "Region": "[REGION]"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "[YOUR COGNITO DOMAIN ]",
              "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
              "SignInRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN IN, e.g. myapp://]",
              "SignOutRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN OUT, e.g. myapp://]",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            }
          }
        }
      }
    }
  }
}
```

File: src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx [hunk 22]
```diff
@@ -0,0 +1,155 @@
...
+                                "profile",
+                                "aws.cognito.signin.user.admin"
+                            ]
+                        }
+                    }
+                }
+            }
+        }
+    }
+}''';
```
Comment (tannerabread) [inline src/fragments/lib/auth/flutter/getting_started/70_configureBackend.mdx:133]:
```suggestion
const amplifyconfig = ''' {
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "[COGNITO IDENTITY POOL ID]",
              "Region": "[REGION]"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "[COGNITO USER POOL ID]",
            "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
            "Region": "[REGION]"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "[YOUR COGNITO DOMAIN ]",
              "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
              "SignInRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN IN, e.g. myapp://]",
              "SignOutRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN OUT, e.g. myapp://]",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            }
          }
        }
      }
    }
  }
}''';
```

File: src/fragments/lib/auth/ios/getting_started/50_configureBackend.mdx [hunk 23]
```diff
@@ -0,0 +1,154 @@
...
+                                "profile",
+                                "aws.cognito.signin.user.admin"
+                            ]
+                        }
+                    }
+                }
+            }
+        }
+    }
+}
```
Comment (tannerabread) [inline src/fragments/lib/auth/ios/getting_started/50_configureBackend.mdx:131]:
```suggestion
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "[COGNITO IDENTITY POOL ID]",
              "Region": "[REGION]"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "[COGNITO USER POOL ID]",
            "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
            "Region": "[REGION]"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "[YOUR COGNITO DOMAIN ]",
              "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
              "SignInRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN IN, e.g. myapp://]",
              "SignOutRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN OUT, e.g. myapp://]",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            }
          }
        }
      }
    }
  }
}
```

File: src/fragments/lib/auth/js/getting-started.mdx [hunk 24]
```diff
@@ -50,6 +96,97 @@ import awsconfig from './aws-exports';
...
+         // OPTIONAL - Hosted UI configuration
+        oauth: {
+            domain: 'your_cognito_domain',
+            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
+            redirectSignIn: 'http://localhost:3000/',
+            redirectSignOut: 'http://localhost:3000/',
+            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
+        }
+    }
+});
```
Comment (tannerabread) [inline src/fragments/lib/auth/js/getting-started.mdx:170]:
```suggestion
Amplify.configure({
  Auth: {
    // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
    identityPoolId: "XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab",

    // REQUIRED - Amazon Cognito Region
    region: "XX-XXXX-X",

    // OPTIONAL - Amazon Cognito Federated Identity Pool Region
    // Required only if it's different from Amazon Cognito Region
    identityPoolRegion: "XX-XXXX-X",

    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: "XX-XXXX-X_abcd1234",

    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: "a1b2c3d4e5f6g7h8i9j0k1l2m3",

    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    mandatorySignIn: false,

    // OPTIONAL - This is used when autoSignIn is enabled for Auth.signUp
    // 'code' is used for Auth.confirmSignUp, 'link' is used for email link verification
    signUpVerificationMethod: "code", // 'code' | 'link'

    // OPTIONAL - Configuration for cookie storage
    // Note: if the secure flag is set to true, then the cookie transmission requires a secure protocol
    cookieStorage: {
      // REQUIRED - Cookie domain (only required if cookieStorage is provided)
      domain: ".yourdomain.com",
      // OPTIONAL - Cookie path
      path: "/",
      // OPTIONAL - Cookie expiration in days
      expires: 365,
      // OPTIONAL - See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
      sameSite: "strict" | "lax",
      // OPTIONAL - Cookie secure flag
      // Either true or false, indicating if the cookie transmission requires a secure protocol (https).
      secure: true,
    },

    // OPTIONAL - customized storage object
    storage: MyStorage,

    // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
    authenticationFlowType: "USER_PASSWORD_AUTH",

    // OPTIONAL - Manually set key value pairs that can be passed to Cognito Lambda Triggers
    clientMetadata: { myCustomKey: "myCustomValue" },

    // OPTIONAL - Hosted UI configuration
    oauth: {
      domain: "your_cognito_domain",
      scope: [
        "phone",
        "email",
        "profile",
        "openid",
        "aws.cognito.signin.user.admin",
      ],
      redirectSignIn: "http://localhost:3000/",
      redirectSignOut: "http://localhost:3000/",
      responseType: "code", // or 'token', note that REFRESH token will only be generated when the responseType is code
    },
  },
});
```

File: src/fragments/lib/auth/js/getting-started.mdx [hunk 25]
```diff
@@ -50,6 +96,97 @@ import awsconfig from './aws-exports';
...
+
+// You can get the current config object
+const currentConfig = Auth.configure();
+```
+<Callout warning={true}>
+If your existing UserPool client has a required attribute that is NOT set to mutable, you may face login issues when using Social sign in. To resolve this, you will need to <ExternalLink href="https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html">create a new UserPool client</ExternalLink> and mark the required attribute as mutable.
```
Comment (tannerabread) [inline src/fragments/lib/auth/js/getting-started.mdx:176]:
```suggestion
If your existing UserPool client has a required attribute that is NOT set to mutable, you may face login issues when using Social sign-in. To resolve this, you will need to <ExternalLink href="https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html">create a new UserPool client</ExternalLink> and mark the required attribute as mutable.
```

**Review by tannerabread — CHANGES_REQUESTED** [review]
[Rule # 21](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md#21-use-2-space-indents-for-code-blocks) for the indent spacing and one nit

**Review by tannerabread — APPROVED** [review]
LGTM

**Review by abdallahshaban557 — APPROVED** [review]
LGTM

**Review by stocaaro — APPROVED** [review]

**Review by katiegoines — APPROVED** [review]
